# Generated by Django 5.0.1 on 2024-01-31 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='Номер')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('password', models.CharField(max_length=64, verbose_name='Пароль')),
                ('bank', models.FloatField(blank=True, default=0.0, verbose_name='Счет')),
                ('rating', models.FloatField(blank=True, default=5.0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='Номер')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('password', models.CharField(max_length=64, verbose_name='Пароль')),
                ('bank', models.FloatField(blank=True, default=0.0, verbose_name='Счет')),
                ('rating', models.FloatField(blank=True, default=5.0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Taxist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='Номер')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('password', models.CharField(max_length=64, verbose_name='Пароль')),
                ('bank', models.FloatField(blank=True, default=0.0, verbose_name='Счет')),
                ('rating', models.FloatField(blank=True, default=5.0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Таксист',
                'verbose_name_plural': 'Таксист',
                'ordering': ['-rating'],
            },
        ),
    ]
