# Generated by Django 5.0.1 on 2024-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_taxist_geoposition_taxist_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='geoposition',
            field=models.CharField(default='49.8000567 73.0895435', max_length=120, verbose_name='Локация'),
        ),
    ]
