# Generated by Django 5.0.1 on 2024-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_courier_geoposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='geoposition',
            field=models.CharField(default='49.8000567 73.0895435', max_length=120, verbose_name='Локация'),
        ),
    ]
