# Generated by Django 5.0.1 on 2024-02-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiorder',
            name='number',
            field=models.CharField(max_length=12, verbose_name='Номер'),
        ),
    ]
