# Generated by Django 5.0.1 on 2024-02-01 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_taxiorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiorder',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='taxiorder',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Начало'),
        ),
    ]
