# Generated by Django 5.0.1 on 2024-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_taxiorder_end_taxiorder_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiorder',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
